### ISSUE TITLE
Mendix-Marketplace

### ISSUE THREAD

**Issue by Hamilkar247** [Itvisors/mendix-NativeTileContainer#1]
Hi thanks for your work - i looked something with tile and i find you at mendix marketplace but  ...
I can't find your elements inside application after instalation. I am begginer at mendix but i think for other could be very helpful simple tutorial with screenshot very we should looking for elements.

**Comment by mgroeneweg** [comment]
Hi,

There will be a tile container widget in your toolbox. The test folder of this github repo has a fully working test app, you can download the entire repo as zip file, extract it on your system and run the Mendix project in the test folder.

As there is no issue with the component I will close this issue.

Good luck.
